apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fibapi
  template:
    metadata:
      labels:
        app: fibapi
    spec:
      containers:
      - name: fibapi
        image: henrsand/fibapi:bda3ffba9f47edcd31d86e28e83180588f0d85bd
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5