apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  # Optional: Add finalizers to cascade delete
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/henrsand/helloargo
    targetRevision: main
    path: argocd  # Points to the directory containing child app definitions
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  # Child Applications will be created in argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true