name: mystarter-frontend

image:
  repository: henrsand/mystarter-frontend
  tag: "81f2545f0f7055baf54cb643c4fca2033bf88e0c"

replicas: 2

containerPort: 80

service:
  port: 80
  targetPort: 80

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

probes:
  liveness:
    path: /
    port: 80
    initialDelaySeconds: 20
    periodSeconds: 5
  readiness:
    path: /
    port: 80
    initialDelaySeconds: 15
    periodSeconds: 5

configMap:
  data:
    VITE_ENVIRONMENT: "Argo"